name: Create Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'donotdownload-release.zip'
        exclusions: '*.git*'
    - uses: ncipollo/release-action@v1
      with:
          artifacts: "donotdownload-release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
